### ISSUE TITLE
define a Scala function in execution plan

### ISSUE THREAD

**Issue by gabrywu** [wso2-attic/product-cep#291]
When I define a Scala function in execution plan, it doesn't work very well.The error message is as follows:

Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception [An exception occurred processing JSP page /siddhitryit/siddhiProcessor_ajaxprocessor.jsp at line 35

32:     JsonObject jsonObject = new JsonObject();
33: 
34:     try {
35:         Map<String, StringBuilder> map = siddhiTryItClientObject.processData(executionplan, eventStream, dateTime);
36:         Object[] resultMapKeysArray = map.keySet().toArray();
37:         Object[] resultMapValuesArray = map.values().toArray();
38: 

Stacktrace:] with root cause
java.lang.ClassNotFoundException: scala.reflect.api.TypeCreator cannot be found by siddhi-extension-eval-script_3.1.2

How can i solve it?

**Comment by tishan89** [comment]
1. Can you describe the steps you followed to define scala function and then invoke it
2. Can you provide the execution plan you are using.

Using above two we can try to reproduce your issue and suggest resolution

**Comment by gabrywu** [comment]
1.  I copy scala-compiler-2.11.0.jar,scala-library-2.11.0.jar,scala-reflect-2.11.0.jar,scalascriptengine_2.11-1.3.10.jar to wso2cep-4.2.0/repository/components/lib 

2.  Restart the server

3.  do as follows

![wso2](https://cloud.githubusercontent.com/assets/8545796/26239748/d98afc78-3cb0-11e7-9f9e-1b380b280c92.png)

4.  The error message is as follows

 Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception [An exception occurred processing JSP page /siddhitryit/siddhiProcessor_ajaxprocessor.jsp at line 35

32:     JsonObject jsonObject = new JsonObject();
33: 
34:     try {
35:         Map<String, StringBuilder> map = siddhiTryItClientObject.processData(executionplan, eventStream, dateTime);
36:         Object[] resultMapKeysArray = map.keySet().toArray();
37:         Object[] resultMapValuesArray = map.values().toArray();
38: 


Stacktrace:] with root cause
java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaUniverse$JavaMirror;

**Comment by gabrywu** [comment]
![wso2](https://cloud.githubusercontent.com/assets/8545796/26239909/a72a12ea-3cb1-11e7-9c13-eec078644f98.png)

**Comment by gabrywu** [comment]
nobody here?

**Comment by tishan89** [comment]
Sorry I missed the thread. Will look into this and update you

**Comment by tishan89** [comment]
@anugayan Can you please look into this issue.
